const Discord = require('discord.js');
const client = new Discord.Client();
const auth = require('./auth.json');

client.on('ready', () => {
    console.log(`Logged in as ${client.user.tag}!`);
});

client.login(auth.token);

client.on('message', msg => {
    console.dir(msg);
    if (msg.content === 'ping') {
        msg.reply('pong');
    }
});

Message {
    channel: TextChannel {
        type: 'text',
        deleted: false,
        id: '617815698382520358',
        name: 'bot-testing',
        position: 2,
        parentID: '616989523322339338',
        permissionOverwrites: Collection[Map] {},
        topic: null,
        nsfw: false,
        lastMessageID: '617816316426059786',
        lastPinTimestamp: null,
        rateLimitPerUser: 0,
        guild: Guild {
            members: [Collection],
            channels: [Collection],
            roles: [Collection],
            presences: [Collection],
            deleted: false,
            available: true,
            id: '616989522231558175',
            name: 'terraria',
            icon: '96b4411a79da78df123d1476b32e391d',
            splash: null,
            region: 'us-east',
            memberCount: 4,
            large: false,
            features: [],
            applicationID: null,
            afkTimeout: 300,
            afkChannelID: null,
            systemChannelID: null,
            embedEnabled: undefined,
            verificationLevel: 0,
            explicitContentFilter: 0,
            mfaLevel: 0,
            joinedTimestamp: 1567276447255,
            defaultMessageNotifications: 'ALL',
            ownerID: '598566240260325427',
            _rawVoiceStates: Collection[Map] {},
            emojis: Collection[Map] {}
        },
        messages: Collection[Map] {
            '617816316426059786' => [Circular]
        },
        _typing: Map {}
    },
    deleted: false,
    id: '617816316426059786',
    type: 'DEFAULT',
    content: 'blah blah blah',
    author: User {
        id: '241021706687348736',
        username: 'pdodd',
        discriminator: '3618',
        avatar: 'e5ea66ac68e98f88427c3e5dace54ea4',
        bot: false,
        lastMessageID: '617816316426059786',
        lastMessage: [Circular]
    },
    member: GuildMember {
        guild: Guild {
            members: [Collection],
            channels: [Collection],
            roles: [Collection],
            presences: [Collection],
            deleted: false,
            available: true,
            id: '616989522231558175',
            name: 'terraria',
            icon: '96b4411a79da78df123d1476b32e391d',
            splash: null,
            region: 'us-east',
            memberCount: 4,
            large: false,
            features: [],
            applicationID: null,
            afkTimeout: 300,
            afkChannelID: null,
            systemChannelID: null,
            embedEnabled: undefined,
            verificationLevel: 0,
            explicitContentFilter: 0,
            mfaLevel: 0,
            joinedTimestamp: 1567276447255,
            defaultMessageNotifications: 'ALL',
            ownerID: '598566240260325427',
            _rawVoiceStates: Collection[Map] {},
            emojis: Collection[Map] {}
        },
        user: User {
            id: '241021706687348736',
            username: 'pdodd',
            discriminator: '3618',
            avatar: 'e5ea66ac68e98f88427c3e5dace54ea4',
            bot: false,
            lastMessageID: '617816316426059786',
            lastMessage: [Circular]
        },
        joinedTimestamp: 1567183474018,
        _roles: ['617426417873059870'],
        serverDeaf: false,
        serverMute: false,
        selfMute: undefined,
        selfDeaf: undefined,
        voiceSessionID: undefined,
        voiceChannelID: undefined,
        speaking: false,
        nickname: null,
        lastMessageID: '617816316426059786',
        lastMessage: [Circular],
        deleted: false
    },
    pinned: false,
    tts: false,
    nonce: '617816319986761728',
    system: false,
    embeds: [],
    attachments: Collection[Map] {},
    createdTimestamp: 1567369288308,
    editedTimestamp: null,
    reactions: Collection[Map] {},
    mentions: MessageMentions {
        everyone: false,
        users: Collection[Map] {},
        roles: Collection[Map] {},
        _content: 'blah blah blah',
        _client: Client {
            _events: [Object],
            _eventsCount: 4,
            _maxListeners: 10,
            options: [Object],
            rest: [RESTManager],
            dataManager: [ClientDataManager],
            manager: [ClientManager],
            ws: [WebSocketManager],
            resolver: [ClientDataResolver],
            actions: [ActionsManager],
            voice: [ClientVoiceManager],
            shard: null,
            users: [Collection],
            guilds: [Collection],
            channels: [Collection],
            presences: Collection[Map] {},
            user: [ClientUser],
            readyAt: 2019 - 09 - 01 T20: 21: 24.040 Z,
            broadcasts: [],
            pings: [Array],
            _timeouts: [Set],
            _intervals: [Set]
        },
        _guild: Guild {
            members: [Collection],
            channels: [Collection],
            roles: [Collection],
            presences: [Collection],
            deleted: false,
            available: true,
            id: '616989522231558175',
            name: 'terraria',
            icon: '96b4411a79da78df123d1476b32e391d',
            splash: null,
            region: 'us-east',
            memberCount: 4,
            large: false,
            features: [],
            applicationID: null,
            afkTimeout: 300,
            afkChannelID: null,
            systemChannelID: null,
            embedEnabled: undefined,
            verificationLevel: 0,
            explicitContentFilter: 0,
            mfaLevel: 0,
            joinedTimestamp: 1567276447255,
            defaultMessageNotifications: 'ALL',
            ownerID: '598566240260325427',
            _rawVoiceStates: Collection[Map] {},
            emojis: Collection[Map] {}
        },
        _members: null,
        _channels: null
    },
    webhookID: null,
    hit: null,
    _edits: []
}